version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: muazzamaida
      MYSQL_DATABASE: djangocalendar
      MYSQL_USER: djangocalendar_user
      MYSQL_PASSWORD: muazzamaida
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  setup-script:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: setup_script
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: djangocalendar
      DB_USER: root
      DB_PASSWORD: muazzamaida
    command: ["python", "database/mysql_setup/mysql_setup.py"]
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
